name: Projects
# 触发器
on:
  schedule:
    - cron: 0 19 * * * #每天在国际标准时间19点(北京时间+8，即 03:00)
  workflow_dispatch:

jobs:
  build:
    runs-on: Ubuntu-22.04
    steps:
      # 检出代码
    - uses: actions/checkout@v3
      # 删除旧的工作流
    - name: Delete action workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0 # 
        keep_minimum_runs: 1 # 
        
    - name: Clone project
      run: |
        git clone --depth=1 https://github.com/PeterNjeim/MagiskOnWSA Projects
        cp -rf Projects/* ${{ github.workspace }}
        cp -rf Projects/.github/workflows/* ${{ github.workspace }}/.github/
        rm -rf Projects
    - name: Update files
      uses: EndBug/add-and-commit@v9
      with:        
        default_author: github_actions
        message: 'update files'
        add: ${{ github.workspace }}/*
